export const CREATE_ELEMENT = "CREATE_ELEMENT";
export const RETRIEVE_ELEMENTS = "RETRIEVE_ELEMENTS";
export const UPDATE_ELEMENT = "UPDATE_ELEMENT";
export const DELETE_ELEMENT = "DELETE_ELEMENT";
export const DELETE_ALL_ELEMENTS = "DELETE_ALL_ELEMENTS";