# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Coveralls 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coveralls:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder:
          - 'backend'
          - 'frontend'
    
    defaults:
      run:
        working-directory:  ./${{ matrix.folder }}

    steps:
    - name: Cloning repo
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache-dependency-path: ${{ matrix.folder }}/package-lock.json
    - name: Installing dependencies
      run: npm install
    - name: Generating coverage information
      run: npm run coveralls
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{ github.workspace }}/${{ matrix.folder }}/coverage/lcov.info

